### ISSUE TITLE
Sample Code Hangs / Doesn't return to command line prompt.   "There are 13 handle(s) keeping the process running."

### ISSUE THREAD

**Issue by TREVORPINKS** [CheshireCaat/playwright-with-fingerprints#44] opened 2024-09-15 16:25 UTC
1.) Copy pasted sample code into a new project.  ie. 
   > npm i playwright-with-fingerprints
   > npm i playwright
   > npx playwright install  
2.) Ran code from console.
3.) code launched browser, navigated to a page etc, then closed the browser.
4.) After the browser closed, the console application did not return to the command line prompt.  It just waited.  
5.) I confirmed error doesn't happen when 'playwright-with-fingerprints' excluded from code.  
6.) I confirmed error still happens regardless of whether launch or plugin.launchPersistentContext is used. 
7.) I added a npm package, 'why-is-node-running' and i got the message that  "There are 13 handle(s) keeping the process running."  It seems like when browser.close is called the code isn't smart enough to catch this and shut everything down and return.      

Is there a work around like calling something just after browser.close()?     

**PART OF THE OUTPUT**

# TTYWRAP
(unknown stack trace)

# DNSCHANNEL
(unknown stack trace)

# PROCESSWRAP
node_modules\bas-remote-node\src\services\engine.js:111                 - this._process = execFile(
node_modules\bas-remote-node\src\services\engine.js:58                  - this._runEngineProcess(port);
node_modules\bas-remote-node\src\index.js:142                           - await this._engine.start(port);
node_modules\browser-with-fingerprints\src\plugin\connector\index.js:41 - await client.start();

# PIPEWRAP
node_modules\bas-remote-node\src\services\engine.js:111 - this._process = execFile(
node_modules\bas-remote-node\src\services\engine.js:58  - this._runEngineProcess(port);

# PIPEWRAP
node_modules\bas-remote-node\src\services\engine.js:111 - this._process = execFile(
node_modules\bas-remote-node\src\services\engine.js:58  - this._runEngineProcess(port);

# PIPEWRAP
node_modules\bas-remote-node\src\services\engine.js:111 - this._process = execFile(
node_modules\bas-remote-node\src\services\engine.js:58  - this._runEngineProcess(port);

# TCPWRAP
node_modules\ws\lib\websocket.js:1054                  - return net.connect(options);
node_modules\ws\lib\websocket.js:868                   - req = websocket._req = request(opts);
node_modules\ws\lib\websocket.js:88                    - initAsClient(this, address, protocols, options);
node_modules\bas-remote-node\src\services\socket.js:27 - createWebSocket: (url) => new WebSocket(url),

# FILEHANDLE
(unknown stack trace)

# FILEHANDLE
(unknown stack trace)

# FILEHANDLE
(unknown stack trace)

# FILEHANDLE
(unknown stack trace)

**SAMPLE CODE:**
const { plugin } = require('playwright-with-fingerprints');

// Set the service key for the plugin (you can buy it here https://bablosoft.com/directbuy/FingerprintSwitcher/2).
// Leave an empty string to use the free version.
plugin.setServiceKey('');

(async () => {
  // Get a fingerprint from the server:
  const fingerprint = await plugin.fetch({
    tags: ['Microsoft Windows', 'Chrome'],
  });

  // Apply fingerprint:
  plugin.useFingerprint(fingerprint);

  // Launch the browser instance:
  const browser = await plugin.launch();

  // The rest of the code is the same as for a standard `playwright` library:
  const page = await browser.newPage();
  await page.goto('https://example.com');

  // Print the browser viewport size:
  console.log(
    'Viewport:',
    await page.evaluate(() => ({
      deviceScaleFactor: window.devicePixelRatio,
      width: document.documentElement.clientWidth,
      height: document.documentElement.clientHeight,
    }))
  );

  await browser.close();
})();

**Comment by CheshireCaat** [comment] 2024-09-15 17:03
The internal client for communication with the engine is automatically closed after 5 minutes, until then it keeps the connection.

Unfortunately, there is currently no method that would force it to close, while you can do it manually, for example, patching [this](https://github.com/CheshireCaat/browser-with-fingerprints/blob/master/src/plugin/connector/index.js) file and add an export for the client instance.

Alternatively, a simpler option is to kill the **FastExecuteScript** process.

**Comment by TREVORPINKS** [comment] 2024-09-15 23:28
I don't want to kill a process because that's hacky.   and It's a bit off I can't close everything when I want to so I want to fix this. 

I am trying to think of a strategy where I would still be able to pull the latest version of the package in the future (without having to re-add my custom changes again).

**Comment by TREVORPINKS** [comment] 2024-09-16 08:45
Here is what I did.  

**Change #1 - browser-with-fingerprints\src\index.d.ts**
_Added a dispose method_

export declare class FingerprintPlugin {
   dispose(): Promise<void>;


**Change #2 - browser-with-fingerprints\src\plugin\index.js**
_Added a dispose method_

//A. import close from connector
const { setup, fetch, versions, setEngineOptions, close } = require('./connector');

//B. added dispose method to FingerprintPlugin class
module.exports = class FingerprintPlugin {

  async dispose()
  {
    console.log('Releasing Resources...')
    close();
  }


**Change #3 - browser-with-fingerprints\src\plugin\connector\index.js**

Added this code to the bottom of the file:  

exports.close = () => dispose();

async function closeClient()
{
  if (client) 
  {
    await client.close();
  }
}

async function dispose() 
{
  return await lock.acquire('client', async () => 
  {
    closeClient();
  });
}


Now I can exit right away after running.  I think you should consider adding a dispose method like this to the code base.

**Comment by CheshireCaat** [comment] 2024-09-16 08:53
I made the close method too (CheshireCaat/browser-with-fingerprints@7ae8cfb), but it will be released later when I update the browser version, your option is also suitable.

**Comment by TREVORPINKS** [comment] 2024-09-16 08:56
OK Awesome.  I'll test it when you release.  Just reply to me here.

**Comment by CheshireCaat** [comment] 2024-10-04 03:11
The engine has been heavily rewritten, now there is no permanent connection with the engine, therefore the closing method is no longer needed.

**Closed by CheshireCaat** 2024-10-04 03:11 UTC

**Comment by TREVORPINKS** [comment] 2024-10-07 09:55
OK - I tested, the main scenario works where it's someone clicking 'x' to close the browser or where my code closes the browser.  But...   When I break using CTRL-C the program doesn't exit to the terminal anymore.  

Did you consider adding your 'shut down / resource release logic' on a CTRL-C?   I basically had a signalListener function that would call the browser.Close() method I added.   

      logger.trace('Attaching SIGINT/SIGTERM listeners');
      if (!process.listeners('SIGINT').includes(signalListener)) {
        process.on('SIGINT', signalListener);
      }
    
      if (!process.listeners('SIGTERM').includes(signalListener)) {
        process.on('SIGTERM', signalListener);
      }

**Comment by CheshireCaat** [comment] 2024-10-07 10:08
Can you give an example of code that will not be completed by CTRL-C?

I tested a simple code to get a fingerprint - it exit correctly (used terminal in VSCode).

There is no additional signal processing in the plugins, but now the engine process is terminated automatically upon completion of a particular request.

In other cases, I specifically used `unref` on timeouts and intervals.

**Comment by TREVORPINKS** [comment] 2024-10-07 11:54
OK Thanks for confirming so quickly.  I tested this scenario further and i learned that it was just my logger (pino) flushing to the terminal (after pressing ctrl-c and seeing the terminal).  So...  nothing was hanging...  i just had to press enter to see my command prompt again.    looks like CTRL-C is covered in your fix just fine.  Thanks again.

**Comment by CheshireCaat** [comment] 2024-10-07 11:56
Great, glad the problem is solved.
