### ISSUE TITLE
Failed to get proxy ip

### ISSUE THREAD

**Issue by dr3adx** [CheshireCaat/playwright-with-fingerprints#14] opened 2023-07-28 17:31 UTC
I tried multiple machines, same error
Even my home IP errors

Wtf is going on? It was working fine until yesterday!

**Comment by bablosoft** [comment] 2023-07-28 17:43
Please avoid opening tickets with just error string and be polite.

> Failed to get proxy ip

This usually means that there is issue with resolving your external ip.

I don't see any issues on server, so depending on your configuration:

1) Check your proxies, if they have access to ip.bablosoft.com
2) Check your internet connection.
3) Check if you input proxies correctly.

**Closed by bablosoft** 2023-07-28 17:43 UTC

**Comment by dr3adx** [comment] 2023-07-28 18:02
@bablosoft             plugin.useProxy(proxy, { changeBrowserLanguage: false, changeGeolocation: true })

**your server has problem 100%** even if you enter empty quotes '' as proxy it will error, even my home IP doesnt work
pinging ip.bablosoft.com works fine 100%. im telling you **i had bot running for days** and today is started erroring

**Comment by bablosoft** [comment] 2023-07-28 18:30
![](https://i.imgur.com/LudKUg2.png)

![](https://i.imgur.com/WszOVxj.png)

I don't see any issues with service.

The advice is still the same as in following comment https://github.com/CheshireCaat/playwright-with-fingerprints/issues/14#issuecomment-1656095204

If you would provide more info, we will be happy to help

**Comment by dr3adx** [comment] 2023-07-28 19:00
@bablosoft ofcourse website checker shows no issue!
because problem is when your server checks the IP (or whatever .useProxy function does) and returns response to client

now everything works fine again so it was problem with server 100%, you should check whats going on with your servers, im a software developer not a noob who doesnt know where the problem is

**Comment by bablosoft** [comment] 2023-07-28 19:24
> because problem is when your server checks the IP (or whatever .useProxy function does) and returns response to client

This is done by http request, exctly which is shown on screenshots.

> now everything works fine again so it was problem with server 100%

I don't see how one follows from the other.

> you should check whats going on with your servers, im a software developer not a noob who doesnt know where the problem is

I've checked servers and reported about that in a first message:

> I don't see any issues on server

**Comment by dr3adx** [comment] 2023-07-28 20:18
@bablosoft im not talking about http req, im talking about whats going on behind http request, the internal checking logic, you check proxy and return response, you should deeply **investigate** why it returns message "**Failed to get proxy ip**"

again, i repeat, i tested this from multiple IPs and different machines with no change to my code in days, so its 100% not issue on my end

**Comment by dr3adx** [comment] 2023-07-28 20:33
@bablosoft look, new error from your server:
![bas error](https://github.com/CheshireCaat/playwright-with-fingerprints/assets/4398836/6f75d748-32ad-481f-8100-34917db511e6)

this can never be issue on my side, please investigate this properly

**Comment by bablosoft** [comment] 2023-07-28 20:35
> im not talking about http req, im talking about whats going on behind http request, the internal checking logic, you check proxy and return response

Getting external ip is done through http request.

> you should deeply investigate why it returns message "Failed to get proxy ip"

Based on your description that you have provide, the problem is somewhere on your side. In order to do more advanced investigation, we need more information about your case.

curl output, minimal source code all of that will be useful.

Again, please don't open tickets with just error string furthermore.

**Comment by bablosoft** [comment] 2023-07-28 20:36
> this can never be issue on my side, please investigate this properly, this is clearly 100% server issue

Please provide more info.

**Comment by dr3adx** [comment] 2023-07-28 20:44
> > this can never be issue on my side, please investigate this properly, this is clearly 100% server issue
> 
> Please provide more info.

your server is returning wrong response, html instead of json (bas-remote-node) you can see it in the photo
you can start by checking logs of all failed requests on your server

**Comment by bablosoft** [comment] 2023-07-28 21:00
> your server is returning wrong response, html instead of json (bas-remote-node) you can see it in the photo
you can start by checking logs of all failed requests and error logs on your server

I mean not how to fix it, but how to reproduce it.

Further communication is possible only you provide some meaningful steps.

**Comment by dr3adx** [comment] 2023-07-30 07:05
@bablosoft its literally the simplest program to launch a fingerprint session, no custom stuff, take code from examples
i told you its not about the program its the .setProxy function that caused errors
